<?php

namespace Creativestyle\ContentConstructorFrontendExtension\DataProviders\ComponentsList;

class ITWindowWidthSlider
{
    use GetDataProviderBlocks;

    public function __construct()
    {
        $this->blocks = [
            0 => [
                'id' => 'component87b9',
                'section' => 'content',
                'type' => 'headline',
                'data' => [
                    'title' => 'IMAGE TEASERS FOR WINDOW WIDTH SLIDER',
                    'subtitle' => '',
                ],
            ],
            2 => [
                'id' => 'component2967',
                'section' => 'content',
                'type' => 'image-teaser',
                'data' => [
                    'items' => [
                        0 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYmFubmVyXzMuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/banner_3.jpg"}}',
                            'displayVariant' => '1',
                            'headline' => '2 in row',
                            'subheadline' => 'Slider',
                            'paragraph' => 'Text on image',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'colorScheme' => 'dark',
                        ],
                        1 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYmFuZXIyLmpwZyJ9fQ',
                            'decodedImage' => '{{media url="creative_components/baner2.jpg"}}',
                            'headline' => 'Headine',
                            'paragraph' => '',
                            'ctaLabel' => 'More',
                            'href' => '',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'displayVariant' => '1',
                            'subheadline' => 'Subheadline',
                            'colorScheme' => 'light',
                        ],
                    ],
                    'ignoredItems' => [],
                    'currentScenario' => [
                        'teaserWidth' => [
                            'name' => 'Window width Slider',
                            'iconId' => 'tw_window-slider',
                            'disabled' => '',
                            'teasersLimit' => '',
                            'id' => 'w-s',
                        ],
                        'desktopLayout' => [
                            'name' => '2 in row',
                            'iconId' => 'dl_2',
                            'disabled' => '',
                            'teasersNum' => '2',
                            'id' => '2',
                        ],
                        'textPositioning' => [
                            'name' => 'Text over image',
                            'iconId' => 'tl_over',
                            'disabled' => '',
                            'textPosition' => '1',
                            'id' => 'over',
                        ],
                        'mobileLayout' => [
                            'name' => 'Slider',
                            'iconId' => 'ml_slider',
                            'disabled' => '',
                            'id' => 'slider',
                        ],
                    ],
                ],
            ],
            3 => [
                'id' => 'component68d9',
                'section' => 'content',
                'type' => 'image-teaser',
                'data' => [
                    'items' => [
                        0 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYmFubmVyXzMuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/banner_3.jpg"}}',
                            'displayVariant' => '1',
                            'headline' => '2 in row',
                            'subheadline' => 'Slider',
                            'paragraph' => 'Text under image',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'colorScheme' => 'dark',
                        ],
                        1 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYmFuZXIyLmpwZyJ9fQ',
                            'decodedImage' => '{{media url="creative_components/baner2.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'More',
                            'href' => '',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'subheadline' => 'Subheadline',
                            'colorScheme' => 'dark',
                            'displayVariant' => '1',
                        ],
                    ],
                    'ignoredItems' => [],
                    'currentScenario' => [
                        'teaserWidth' => [
                            'name' => 'Window width Slider',
                            'iconId' => 'tw_window-slider',
                            'disabled' => '',
                            'teasersLimit' => '',
                            'id' => 'w-s',
                        ],
                        'desktopLayout' => [
                            'name' => '2 in row',
                            'iconId' => 'dl_2',
                            'disabled' => '',
                            'teasersNum' => '2',
                            'id' => '2',
                        ],
                        'textPositioning' => [
                            'name' => 'Text below image',
                            'iconId' => 'tl_under',
                            'disabled' => '',
                            'textPosition' => '',
                            'id' => 'under',
                        ],
                        'mobileLayout' => [
                            'name' => 'Slider',
                            'iconId' => 'ml_slider',
                            'disabled' => '',
                            'id' => 'slider',
                        ],
                    ],
                ],
            ],
            4 => [
                'id' => 'component2269',
                'section' => 'content',
                'type' => 'image-teaser',
                'data' => [
                    'items' => [
                        0 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYmFubmVyXzMuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/banner_3.jpg"}}',
                            'displayVariant' => '1',
                            'headline' => '3 in row',
                            'subheadline' => 'Slider',
                            'paragraph' => 'Text on image',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'colorScheme' => 'dark',
                        ],
                        1 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYmFuZXIyLmpwZyJ9fQ',
                            'decodedImage' => '{{media url="creative_components/baner2.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'More',
                            'href' => '',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'subheadline' => 'Subheadline',
                            'displayVariant' => '1',
                            'colorScheme' => 'dark',
                        ],
                        2 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvc2xpZGUxLmpwZyJ9fQ',
                            'decodedImage' => '{{media url="creative_components/slide1.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'displayVariant' => '1',
                            'colorScheme' => 'light',
                        ],
                    ],
                    'ignoredItems' => [],
                    'currentScenario' => [
                        'teaserWidth' => [
                            'name' => 'Window width Slider',
                            'iconId' => 'tw_window-slider',
                            'disabled' => '',
                            'teasersLimit' => '',
                            'id' => 'w-s',
                        ],
                        'desktopLayout' => [
                            'name' => '3 in row',
                            'iconId' => 'dl_3',
                            'disabled' => '',
                            'teasersNum' => '3',
                            'id' => '3',
                        ],
                        'textPositioning' => [
                            'name' => 'Text over image',
                            'iconId' => 'tl_over',
                            'disabled' => '',
                            'textPosition' => '1',
                            'id' => 'over',
                        ],
                        'mobileLayout' => [
                            'name' => 'Slider',
                            'iconId' => 'ml_slider',
                            'disabled' => '',
                            'id' => 'slider',
                        ],
                    ],
                ],
            ],
            5 => [
                'id' => 'componentaba8',
                'section' => 'content',
                'type' => 'image-teaser',
                'data' => [
                    'items' => [
                        0 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYmFubmVyXzMuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/banner_3.jpg"}}',
                            'displayVariant' => '1',
                            'headline' => '3 in row',
                            'subheadline' => 'Slider',
                            'paragraph' => 'Text below image',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'colorScheme' => 'dark',
                        ],
                        1 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYmFuZXIyLmpwZyJ9fQ',
                            'decodedImage' => '{{media url="creative_components/baner2.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'More',
                            'href' => '',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'subheadline' => 'Subheadline',
                            'displayVariant' => '1',
                            'colorScheme' => 'dark',
                        ],
                        2 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvc2xpZGUxLmpwZyJ9fQ',
                            'decodedImage' => '{{media url="creative_components/slide1.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '1920x1022px (960:511)',
                            'aspectRatio' => '960:511',
                            'displayVariant' => '1',
                            'colorScheme' => 'dark',
                        ],
                    ],
                    'ignoredItems' => [],
                    'currentScenario' => [
                        'teaserWidth' => [
                            'name' => 'Window width Slider',
                            'iconId' => 'tw_window-slider',
                            'disabled' => '',
                            'teasersLimit' => '',
                            'id' => 'w-s',
                        ],
                        'desktopLayout' => [
                            'name' => '3 in row',
                            'iconId' => 'dl_3',
                            'disabled' => '',
                            'teasersNum' => '3',
                            'id' => '3',
                        ],
                        'textPositioning' => [
                            'name' => 'Text below image',
                            'iconId' => 'tl_under',
                            'disabled' => '',
                            'textPosition' => '',
                            'id' => 'under',
                        ],
                        'mobileLayout' => [
                            'name' => 'Slider',
                            'iconId' => 'ml_slider',
                            'disabled' => '',
                            'id' => 'slider',
                        ],
                    ],
                ],
            ],
            6 => [
                'id' => 'component5cbc',
                'section' => 'content',
                'type' => 'image-teaser',
                'data' => [
                    'items' => [
                        0 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvTGF5ZXJfNjdfcmV1cGxvYWQuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/Layer_67_reupload.jpg"}}',
                            'displayVariant' => '1',
                            'headline' => '4 in row',
                            'subheadline' => 'Slider',
                            'paragraph' => 'Text on image',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '574x571px (574:571)',
                            'aspectRatio' => '574:571',
                            'colorScheme' => 'dark',
                        ],
                        1 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvTGF5ZXJfNjZfcmV1cGxvYWQuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/Layer_66_reupload.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'More',
                            'href' => '',
                            'sizeInfo' => '574x571px (574:571)',
                            'aspectRatio' => '574:571',
                            'displayVariant' => '1',
                            'subheadline' => 'Subheadline',
                            'colorScheme' => 'dark',
                        ],
                        2 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvTGF5ZXJfNjZfY29weV8yX3JldXBsb2FkLmpwZyJ9fQ',
                            'decodedImage' => '{{media url="creative_components/Layer_66_copy_2_reupload.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'More',
                            'href' => '',
                            'sizeInfo' => '573x571px (573:571)',
                            'aspectRatio' => '573:571',
                            'displayVariant' => '1',
                            'subheadline' => '',
                            'colorScheme' => 'light',
                        ],
                        3 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvTGF5ZXJfNjdfcmV1cGxvYWQuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/Layer_67_reupload.jpg"}}',
                            'headline' => '',
                            'paragraph' => '',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '574x571px (574:571)',
                            'aspectRatio' => '574:571',
                            'colorScheme' => 'dark',
                            'displayVariant' => '1',
                        ],
                    ],
                    'ignoredItems' => [],
                    'currentScenario' => [
                        'teaserWidth' => [
                            'name' => 'Window width Slider',
                            'iconId' => 'tw_window-slider',
                            'disabled' => '',
                            'teasersLimit' => '',
                            'id' => 'w-s',
                        ],
                        'desktopLayout' => [
                            'name' => '4 in row',
                            'iconId' => 'dl_4',
                            'disabled' => '',
                            'teasersNum' => '4',
                            'id' => '4',
                        ],
                        'textPositioning' => [
                            'name' => 'Text over image',
                            'iconId' => 'tl_over',
                            'disabled' => '',
                            'textPosition' => '1',
                            'id' => 'over',
                        ],
                        'mobileLayout' => [
                            'name' => 'Slider',
                            'iconId' => 'ml_slider',
                            'disabled' => '',
                            'id' => 'slider',
                        ],
                    ],
                ],
            ],
            7 => [
                'id' => 'component29af',
                'section' => 'content',
                'type' => 'image-teaser',
                'data' => [
                    'items' => [
                        0 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvTGF5ZXJfNjdfcmV1cGxvYWQuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/Layer_67_reupload.jpg"}}',
                            'displayVariant' => '1',
                            'headline' => '4 in row',
                            'subheadline' => 'Slider',
                            'paragraph' => 'Text under image',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '574x571px (574:571)',
                            'aspectRatio' => '574:571',
                            'colorScheme' => 'dark',
                        ],
                        1 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvTGF5ZXJfNjZfcmV1cGxvYWQuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/Layer_66_reupload.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'More',
                            'href' => '',
                            'sizeInfo' => '574x571px (574:571)',
                            'aspectRatio' => '574:571',
                            'displayVariant' => '1',
                            'subheadline' => 'Subheadline',
                            'colorScheme' => 'dark',
                        ],
                        2 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvTGF5ZXJfNjZfY29weV8yX3JldXBsb2FkLmpwZyJ9fQ',
                            'decodedImage' => '{{media url="creative_components/Layer_66_copy_2_reupload.jpg"}}',
                            'headline' => 'Headline',
                            'paragraph' => '',
                            'ctaLabel' => 'More',
                            'href' => '',
                            'sizeInfo' => '573x571px (573:571)',
                            'aspectRatio' => '573:571',
                            'displayVariant' => '1',
                            'subheadline' => '',
                            'colorScheme' => 'dark',
                        ],
                        3 => [
                            'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvTGF5ZXJfNjdfcmV1cGxvYWQuanBnIn19',
                            'decodedImage' => '{{media url="creative_components/Layer_67_reupload.jpg"}}',
                            'headline' => '',
                            'paragraph' => '',
                            'ctaLabel' => 'Button',
                            'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                            'sizeInfo' => '574x571px (574:571)',
                            'aspectRatio' => '574:571',
                            'displayVariant' => '1',
                            'colorScheme' => 'dark',
                        ],
                    ],
                    'ignoredItems' => [],
                    'currentScenario' => [
                        'teaserWidth' => [
                            'name' => 'Window width Slider',
                            'iconId' => 'tw_window-slider',
                            'disabled' => '',
                            'teasersLimit' => '',
                            'id' => 'w-s',
                        ],
                        'desktopLayout' => [
                            'name' => '4 in row',
                            'iconId' => 'dl_4',
                            'disabled' => '',
                            'teasersNum' => '4',
                            'id' => '4',
                        ],
                        'textPositioning' => [
                            'name' => 'Text below image',
                            'iconId' => 'tl_under',
                            'disabled' => '',
                            'textPosition' => '',
                            'id' => 'under',
                        ],
                        'mobileLayout' => [
                            'name' => 'Slider',
                            'iconId' => 'ml_slider',
                            'disabled' => '',
                            'id' => 'slider',
                        ],
                    ],
                ],
            ],
        ];
    }
}
